# --------------------------------------
# CREDPAY Payment Service - FastAPI
# --------------------------------------

FROM python:3.14-slim
# Disable output buffering
ENV PYTHONUNBUFFERED=1
# Prevent Python from writing .pyc files
ENV PYTHONDONTWRITEBYTECODE=1
# Set working directory
WORKDIR /app

# Copy dependency file first for Docker layer caching
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy application source
COPY app ./app

ENV DB_USERNAME=postgres \
    DB_HOST=localhost \
    DB_PORT=5432 \
    DB_NAME=credpay 
# Expose FastAPI port
EXPOSE 8000

# Start FastAPI
ENTRYPOINT  ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]